# Generated by Django 5.0.1 on 2024-02-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studymaterial",
            name="file",
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="performance_level",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="sms_recommendations",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
