# Generated by Django 5.0.1 on 2024-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_analysis", "0003_studentperformancedata_delete_studentperformance"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_no", models.CharField(max_length=50)),
                ("student_name", models.CharField(max_length=100)),
                ("subject_name", models.CharField(max_length=100)),
                ("score", models.FloatField()),
            ],
        ),
    ]
